global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ktor-app'
    static_configs:
      - targets: ['ktor-app:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:16686']
    metrics_path: '/metrics'
    scrape_interval: 10s 